// ============================================================
// ASCEND — 100 citazioni motivazionali (filosofi del mondo)
// Usate dal rotatore della Home. Autori principali: stoici, greci,
// orientali, esistenzialisti, moderni.
// ============================================================

export interface Quote {
  text: string;
  author: string;
  origin?: string;
}

export const QUOTES: Quote[] = [
  { text: "Non è che non osiamo perché le cose sono difficili, ma le cose sono difficili perché non osiamo.", author: "Seneca" },
  { text: "La vita è ciò che accade mentre sei occupato a fare altri progetti.", author: "John Lennon" },
  { text: "Chi guarda fuori, sogna; chi guarda dentro, si sveglia.", author: "Carl Gustav Jung" },
  { text: "Il segreto del cambiamento è concentrare tutta la tua energia non sul combattere il vecchio, ma sul costruire il nuovo.", author: "Socrate" },
  { text: "Non possiamo scegliere le circostanze, ma possiamo scegliere le nostre reazioni.", author: "Epitteto" },
  { text: "L'ostacolo è la via.", author: "Marco Aurelio" },
  { text: "Chiunque lotti può perdere. Chi non lotta ha già perso.", author: "Bertolt Brecht" },
  { text: "La disciplina è il ponte tra gli obiettivi e i risultati.", author: "Jim Rohn" },
  { text: "Il miglior momento per piantare un albero era vent'anni fa. Il secondo miglior momento è adesso.", author: "Saggezza cinese" },
  { text: "Un viaggio di mille miglia comincia con un singolo passo.", author: "Lao Tzu" },
  { text: "Fai ciò che puoi, con ciò che hai, dove sei.", author: "Theodore Roosevelt" },
  { text: "Vincere non è tutto, ma voler vincere sì.", author: "Vince Lombardi" },
  { text: "La felicità non è fare sempre ciò che si vuole, ma volere sempre ciò che si fa.", author: "Leonardo da Vinci" },
  { text: "Non piangere perché è finito, sorridi perché è successo.", author: "Dr. Seuss" },
  { text: "L'uomo è condannato a essere libero.", author: "Jean-Paul Sartre" },
  { text: "Nel mezzo della difficoltà nasce l'opportunità.", author: "Albert Einstein" },
  { text: "Chiunque smetta di imparare è vecchio, sia a venti che a ottant'anni. Chi continua a imparare resta giovane.", author: "Henry Ford" },
  { text: "La più grande gloria non è non cadere mai, ma risollevarsi ogni volta che si cade.", author: "Confucio" },
  { text: "Non giudicare ogni giorno dal raccolto che hai, ma dai semi che hai piantato.", author: "Robert Louis Stevenson" },
  { text: "Quello che non ci uccide ci rende più forti.", author: "Friedrich Nietzsche" },
  { text: "Pensa a te stesso come a una montagna: cadi tante volte, ma resti sempre in piedi.", author: "Marco Aurelio" },
  { text: "Non si può attraversare il mare semplicemente guardando l'acqua.", author: "Rabindranath Tagore" },
  { text: "L'unico vero fallimento è non provarci.", author: "Confucio" },
  { text: "La fortuna aiuta gli audaci.", author: "Virgilio" },
  { text: "Ogni giorno è una nuova occasione per cambiare la tua vita.", author: "Gautama Buddha" },
  { text: "La mente è tutto. Diventi ciò che pensi.", author: "Gautama Buddha" },
  { text: "Sii il cambiamento che vuoi vedere nel mondo.", author: "Mahatma Gandhi" },
  { text: "Prima di tutto sii te stesso, poi fai le cose.", author: "Lao Tzu" },
  { text: "Due cose sono infinite: l'universo e la stupidità umana. E sull'universo ho ancora dei dubbi.", author: "Albert Einstein" },
  { text: "Il coraggio è la paura che dice le sue preghiere.", author: "Jean Cocteau" },
  { text: "L'unico modo per fare un grande lavoro è amare ciò che fai.", author: "Steve Jobs" },
  { text: "Non smettere mai di sognare, solo chi sogna può volare.", author: "J.R.R. Tolkien" },
  { text: "La perseveranza non è una lunga corsa; è molte corse brevi una dopo l'altra.", author: "Walter Elliot" },
  { text: "Agisci come se ciò che fai facesse la differenza. La fa.", author: "William James" },
  { text: "Chi ha un perché per vivere può sopportare quasi ogni come.", author: "Friedrich Nietzsche" },
  { text: "La vera grandezza è iniziare da dove gli altri smettono.", author: "Anonimo" },
  { text: "Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.", author: "Eleanor Roosevelt" },
  { text: "Non aspettare. Il momento giusto non arriverà mai.", author: "Napoleon Hill" },
  { text: "Il segreto del tuo futuro è nascosto nella tua routine quotidiana.", author: "Mike Murdock" },
  { text: "L'eccellenza non è un atto, ma un'abitudine.", author: "Aristotele" },
  { text: "La felicità dipende da noi stessi.", author: "Aristotele" },
  { text: "Conosci te stesso.", author: "Socrate" },
  { text: "Una vita non esaminata non merita di essere vissuta.", author: "Socrate" },
  { text: "L'importante non è vivere, ma vivere bene.", author: "Platone" },
  { text: "Il corpo è il tempio dell'anima.", author: "Platone" },
  { text: "Chi vince sé stesso è il più forte dei vincitori.", author: "Cicerone" },
  { text: "Pazienza è l'arte di sperare.", author: "Vauvenargues" },
  { text: "Là dove c'è una volontà, c'è una via.", author: "Proverbio latino" },
  { text: "Fai oggi ciò che gli altri non fanno, domani vivrai come gli altri non possono.", author: "Jerry Rice" },
  { text: "Il dolore è temporaneo, il successo è per sempre.", author: "Anonimo" },
  { text: "Combatti ancora una volta: vinci sempre all'ultimo round.", author: "Muhammad Ali" },
  { text: "Non si può fermare le onde, ma si può imparare a cavalcarle.", author: "Jon Kabat-Zinn" },
  { text: "Siamo ciò che facciamo ripetutamente. L'eccellenza, quindi, non è un atto ma un'abitudine.", author: "Aristotele" },
  { text: "Nessun vento è favorevole per il marinaio che non sa dove andare.", author: "Seneca" },
  { text: "È meglio essere preparati a un'occasione e non averla, che avere un'occasione e non esserci preparati.", author: "Whitney M. Young Jr." },
  { text: "La virtù non abita nella montagna, ma nelle azioni quotidiane.", author: "Epitteto" },
  { text: "Chi domina gli altri è forte; chi domina se stesso è potente.", author: "Lao Tzu" },
  { text: "Il viaggio è la ricompensa.", author: "Proverbio cinese" },
  { text: "La nostra maggior gloria non è non cadere mai, ma rialzarci ogni volta che cadiamo.", author: "Confucio" },
  { text: "Un'ora di intenso impegno vale più di un anno di lamentele.", author: "Rumi" },
  { text: "Ciò che cerchi cerca anche te.", author: "Rumi" },
  { text: "Alzati, sii coraggioso, metti il cuore sopra le difficoltà.", author: "Rumi" },
  { text: "La ferita è il luogo da cui entra la luce.", author: "Rumi" },
  { text: "Non sei una goccia nell'oceano, sei l'oceano in una goccia.", author: "Rumi" },
  { text: "Il successo è la somma di piccoli sforzi ripetuti ogni giorno.", author: "Robert Collier" },
  { text: "Se vuoi qualcosa che non hai mai avuto, devi fare qualcosa che non hai mai fatto.", author: "Thomas Jefferson" },
  { text: "L'arte di vincere si impara nelle sconfitte.", author: "Simon Bolívar" },
  { text: "Il tempo è la moneta della vita.", author: "Benjamin Franklin" },
  { text: "Oggi è il primo giorno del resto della tua vita.", author: "Charles Dederich" },
  { text: "Le grandi cose non si fanno con la forza, ma con la costanza.", author: "Samuel Johnson" },
  { text: "Chi crede di poter fare qualcosa e chi crede di non poterla fare, ha entrambi ragione.", author: "Henry Ford" },
  { text: "Non limitarti. Molte persone si limitano a ciò che pensano di poter fare. Tu puoi andare lontano quanto la tua mente ti consente.", author: "Mary Kay Ash" },
  { text: "Se ascolti il tuo corpo quando sussurra, non lo sentirai quando grida.", author: "Proverbio" },
  { text: "Chi non pianifica sta pianificando di fallire.", author: "Benjamin Franklin" },
  { text: "Il segreto per andare avanti è iniziare.", author: "Mark Twain" },
  { text: "L'energia e la persistenza conquistano tutte le cose.", author: "Benjamin Franklin" },
  { text: "La vita è per il 10% cosa ti accade e per il 90% come reagisci.", author: "Charles R. Swindoll" },
  { text: "Non è la specie più forte a sopravvivere, né la più intelligente, ma quella più adattabile al cambiamento.", author: "Charles Darwin (attribuita)" },
  { text: "Il coraggio non è l'assenza di paura, ma la capacità di agire nonostante essa.", author: "Nelson Mandela" },
  { text: "Ogni maestro è stato prima uno studente. Ogni campione è stato prima un perdente.", author: "Anonimo" },
  { text: "La determinazione di oggi è il successo di domani.", author: "Proverbio" },
  { text: "Sii lento nel giudicare, veloce nel capire.", author: "Proverbio" },
  { text: "Il denaro cresce sull'albero della perseveranza.", author: "Proverbio giapponese" },
  { text: "Cadere sette volte, rialzarsi otto.", author: "Proverbio giapponese" },
  { text: "Chi ha fretta attraversa il guado a rischio di annegare.", author: "Proverbio africano" },
  { text: "Chi vuole, cerca i mezzi. Chi non vuole, cerca le scuse.", author: "Proverbio" },
  { text: "Non puoi cambiare il vento, ma puoi regolare le vele.", author: "Proverbio" },
  { text: "L'unico limite al nostro domani saranno i nostri dubbi di oggi.", author: "Franklin D. Roosevelt" },
  { text: "Ogni giorno porta la sua opportunità: afferrala, ne vale la pena.", author: "Anonimo" },
  { text: "Il successo nasce quando l'opportunità incontra la preparazione.", author: "Seneca (parafrasi)" },
  { text: "Lavora in silenzio, lascia che il successo faccia rumore.", author: "Frank Ocean" },
  { text: "La costanza non è un dovere, è la strategia dei forti.", author: "Anonimo" },
  { text: "Piccoli passi ogni giorno portano a grandi risultati.", author: "Proverbio" },
  { text: "Nessun risultato è mai il punto di arrivo: è sempre il punto di partenza di qualcosa di migliore.", author: "Anonimo" },
  { text: "Il segreto non è correre dietro alle farfalle, ma curare il giardino perché vengano da te.", author: "Proverbio" },
  { text: "Le radici della conoscenza sono amare, ma i frutti sono dolci.", author: "Leonardo da Vinci" },
  { text: "Chi non rischia non beve champagne.", author: "Proverbio francese" },
  { text: "Il coraggio di iniziare è la prima ed essenziale forza del successo.", author: "Aristotele (attribuita)" },
  { text: "Il tuo tempo è limitato, non sprecarlo vivendo la vita di qualcun altro.", author: "Steve Jobs" },
  { text: "Fai della tua vita un'opera d'arte.", author: "Fëdor Dostoevskij" },
  { text: "La disciplina è ricordare ciò che vuoi.", author: "David Campbell" },
];
