// ============================================================
// ASCEND — Data model (sezione 5 della specifica v3)
// Fonte unica di verità per TUTTI i moduli dell'app.
// Nessuna entità definita altrove. NON modificare senza aggiornare db.ts e compute.ts.
// ============================================================

export type PrivacyMode = "off" | "standard" | "complete";

export interface UserSettings {
  baseCurrency: string; // es. "EUR"
  timezone: string; // IANA es. "Europe/Rome"
  weekStart: 0 | 1 | 2 | 3 | 4 | 5 | 6; // 0=domenica, 1=lunedì
  locale: string; // es. "it-IT"
  privacyMode: PrivacyMode;
  onboardingDone: boolean;
  /** saldo iniziale finanze (valuta base) — punto di partenza del conto personale */
  initialBalance?: number;
  lastFreezeMonth?: string; // "yyyy-MM" — streak freeze usato
  updatedAt: string;
}

export type TransactionType = "income" | "expense";

export interface Category {
  id: string;
  name: string;
  type: TransactionType;
  icon: string; // emoji
  color: string; // hex
}

export interface Transaction {
  id: string;
  amount: number; // in valuta della riga (positivo)
  currency: string;
  exchangeRate: number; // unità di valuta base per 1 unità di `currency`, al momento dell'inserimento (1 se uguale alla base)
  type: TransactionType;
  categoryId: string;
  date: string; // "yyyy-MM-dd" — confine giorno in timezone UserSettings
  note?: string;
  recurring?: boolean;
  autoGenerated?: boolean; // es. payout trading → Finanze
  sourcePayoutId?: string | null;
  createdAt: string;
}

export type AccountType = "prop" | "personal";
export type AccountStatus = "eval" | "superato" | "finanziato" | "bruciato";

export interface TradingAccount {
  id: string;
  name: string;
  type: AccountType;
  nativeCurrency: string;
  capital: number;
  status: AccountStatus;
  firm?: string;
  tradingDayTimezone: string; // IANA — confine del trading day
  tradingDayRolloverTime: string; // "17:00"
  dailyLossLimit?: number | null; // valuta nativa
  maxLossLimit?: number | null; // valuta nativa
  /** OBBIETTIVO per account in 'eval': saldo (capitale+pnl chiusi) da raggiungere per la promozione a 'finanziato' */
  evalTarget?: number | null;
  // Convenienza app-level (non nel modello doc): tasso nativo→base quotato
  // quando ≠ base, usato SOLO per aggregare trade in valuta base (il trade
  // non porta valuta: deriva dall'account). Se assente, gli aggregati cross-currency usano 1.
  baseRate?: number | null;
  archived?: boolean;
  createdAt: string;
}

export type TradeDirection = "long" | "short";

export interface Trade {
  id: string;
  accountId: string;
  instrument: string;
  direction: TradeDirection;
  entry?: number | null;
  exit?: number | null;
  size?: number | null;
  stop?: number | null;
  target?: number | null;
  resultNative: number; // valuta nativa dell'account (positivo/negativo)
  resultR: number; // in R
  openDate: string; // ISO datetime
  closeDate: string; // ISO datetime — usato per il raggruppamento in trading day
  screenshots: string[]; // data URL (compressi). Storage limitato su localStorage.
  description?: string;
  setupId?: string | null;
  emotion?: string;
  createdAt: string;
}

export interface Setup {
  id: string;
  name: string;
  createdAt: string;
}

export interface SetupRule {
  id: string;
  setupId: string;
  text: string;
  sortOrder: number;
  active: boolean;
}

export interface TradeSetupRule {
  id: string;
  tradeId: string;
  ruleId: string;
  respected: boolean;
}

export type FirmExpenseType = "eval" | "reset" | "sub";

export interface FirmExpense {
  id: string;
  accountId: string;
  type: FirmExpenseType;
  amount: number;
  currency: string;
  exchangeRate: number;
  date: string;
  note?: string;
  createdAt: string;
}

export interface Payout {
  id: string;
  accountId: string;
  amount: number;
  currency: string;
  exchangeRate: number;
  date: string;
  note?: string;
  createdAt: string;
}

export interface WeeklyReviewStats {
  weekStart: string;
  trades: number;
  winRate: number | null;
  totalR: number;
  totalNative: number;
  profitFactor: number | null;
  disciplinePct: number | null;
  noSetupCount: number;
  pcMinutes: number;
  workouts: number;
  income: number;
  expense: number;
  net: number;
  pagesRead: number;
  ascordWon: number;
  ascordTotal: number;
}

export interface WeeklyReview {
  id: string;
  weekStart: string; // "yyyy-MM-dd" (inizio settimana della review)
  stats: WeeklyReviewStats; // snapshot auto-calcolato
  answer1: string;
  answer2: string;
  answer3: string;
  createdAt: string;
  updatedAt: string;
}

export type GoalType =
  | "finanze_check" // almeno una transazione registrata nel giorno
  | "trade_log" // almeno un trade CHIUSO nel giorno
  | "disciplina_ok" // tutti i trade chiusi del giorno con setup rispettato / nessun trade senza setup
  | "lettura_minuti" // minuti di lettura (conteggiati dal progresso libri del giorno)
  | "allenamento" // almeno un workout nel giorno
  | "ore_produttive"; // minuti produttivi PC >= target

export interface DailyGoal {
  id: string;
  type: GoalType;
  targetValue: number; // 0 = presenza generica ("almeno un'azione"); altrimenti soglia
  active: boolean;
  deadline?: string | null; // "yyyy-MM-dd" — scadenza opzionale (visibile in Home)
}

export interface WeeklyGoal {
  id: string;
  type: GoalType | "workout_count" | "book_pages" | "pc_hours";
  targetValue: number;
  period: "week" | "month";
  active: boolean;
  deadline?: string | null; // "yyyy-MM-dd" — scadenza opzionale
}

export type PCUsageSource = "manuale" | "csv" | "activitywatch" | "auto";

export interface PCUsageLog {
  id: string;
  date: string; // "yyyy-MM-dd"
  categoryId: string;
  minutes: number;
  source: PCUsageSource;
  createdAt: string;
}

export interface PCAppCategoryMap {
  id: string;
  appName: string;
  category: string;
}

export type BookStatus = "da_leggere" | "in_corso" | "finito";

export interface Book {
  id: string;
  title: string;
  author: string;
  status: BookStatus;
  totalPages: number;
  pagesRead: number;
  rating?: number | null;
  notes?: string;
  quotes?: string;
  startDate?: string | null;
  endDate?: string | null;
  createdAt: string;
  updatedAt: string; // usato per conteggiare i minuti di lettura del giorno
}

export interface Workout {
  id: string;
  date: string; // "yyyy-MM-dd"
  type: string;
  durationMin: number;
  note?: string;
  pr?: string;
  createdAt: string;
}

/** Zona Studio — sessioni di studio tracciate */
export interface StudySession {
  id: string;
  date: string; // "yyyy-MM-dd"
  subject: string; // materia
  minutes: number;
  note?: string;
  createdAt: string;
}

/** Risparmi — conto di accumulo progressivo per investimenti futuri */
export interface SavingsGoal {
  id: string;
  name: string;
  target: number; // obiettivo (valuta base)
  deadline?: string | null; // "yyyy-MM-dd"
  active: boolean;
  createdAt: string;
}

export interface SavingsDeposit {
  id: string;
  goalId?: string | null; // opzionale: a quale obiettivo è allocato
  amount: number; // versamento (valuta base)
  date: string; // "yyyy-MM-dd"
  note?: string;
  createdAt: string;
}

export interface Badge {
  key: string;
  unlockedAt: string;
}

// ============================================================
// Database shape (localStorage) — rispecchia la sezione 5
// ============================================================
export interface DB {
  version: number;
  settings: UserSettings;
  categories: Category[];
  transactions: Transaction[];
  accounts: TradingAccount[];
  trades: Trade[];
  setups: Setup[];
  setupRules: SetupRule[];
  tradeSetupRules: TradeSetupRule[];
  firmExpenses: FirmExpense[];
  payouts: Payout[];
  weeklyReviews: WeeklyReview[];
  dailyGoals: DailyGoal[];
  weeklyGoals: WeeklyGoal[];
  pcUsageLogs: PCUsageLog[];
  pcAppCategoryMap: PCAppCategoryMap[];
  books: Book[];
  workouts: Workout[];
  studySessions: StudySession[];
  savingsGoals: SavingsGoal[];
  savingsDeposits: SavingsDeposit[];
  badges: Badge[];
}

export const DB_VERSION = 4;
