"use client";
// ============================================================
// Tabella transazioni del mese (spec 4.2 §4)
// Data · categoria (icona+colore) · nota · importo colorato in base
// (doppio se valuta ≠ base) · badge "auto" (collegamento payout) ·
// toggle ricorrente per riga · eliminazione SOLO della transazione
// (mai il payout collegato).
// ============================================================

import { useState } from "react";
import Link from "next/link";
import { useDB, updateDB, removeById } from "@/lib/storage";
import { monthKeyOf } from "@/lib/dates";
import { getCategory } from "@/lib/db";
import { formatMoney, formatSignedMoney } from "@/lib/format";
import { moneyMasked, maskMoney } from "@/lib/privacy";
import type { Transaction } from "@/lib/types";
import { cn } from "@/lib/cn";
import { Card, CardHeader, CardTitle, CardSubtitle } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { ConfirmDialog } from "@/components/ui/Modal";
import { EmptyState } from "@/components/ui/Misc";

export function TransactionTable({ month }: { month: string }) {
  const db = useDB();
  const base = db.settings.baseCurrency.toUpperCase();
  const locale = db.settings.locale;
  const masked = moneyMasked(db.settings.privacyMode);

  const [toDelete, setToDelete] = useState<Transaction | null>(null);

  const txs = db.transactions
    .filter((t) => monthKeyOf(t.date) === month)
    .sort((a, b) => `${b.date}|${b.createdAt}`.localeCompare(`${a.date}|${a.createdAt}`));

  const confirmDelete = () => {
    if (!toDelete) return;
    updateDB((d) => ({ ...d, transactions: removeById(d.transactions, toDelete.id) }));
    setToDelete(null);
  };

  const toggleRecurring = (t: Transaction) => {
    updateDB((d) => ({
      ...d,
      transactions: d.transactions.map((x) =>
        x.id === t.id ? { ...x, recurring: x.recurring ? undefined : true } : x
      ),
    }));
  };

  const signedBase = (t: Transaction) =>
    t.type === "income" ? t.amount * t.exchangeRate : -(t.amount * t.exchangeRate);

  return (
    <Card>
      <CardHeader>
        <div>
          <CardTitle>Transazioni {month}</CardTitle>
          <CardSubtitle>
            Importi convertiti in {base}
            {!masked && txs.length > 0 && ` · ${txs.length} movimenti`}
          </CardSubtitle>
        </div>
      </CardHeader>

      {txs.length === 0 ? (
        <EmptyState
          icon="🧾"
          title="Nessuna transazione in questo mese"
          description="Registra la prima dal form qui sopra."
        />
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full min-w-[560px] text-sm">
            <thead>
              <tr className="border-b border-border text-left text-[11px] uppercase tracking-wider text-muted-foreground">
                <th className="pb-2 pr-3 font-medium">Data</th>
                <th className="pb-2 pr-3 font-medium">Categoria</th>
                <th className="pb-2 pr-3 font-medium">Nota</th>
                <th className="pb-2 pr-3 text-right font-medium">Importo</th>
                <th className="pb-2 pr-3 text-right font-medium">Ric.</th>
                <th className="pb-2 text-right font-medium" />
              </tr>
            </thead>
            <tbody>
              {txs.map((t) => {
                const cat = getCategory(db, t.categoryId);
                const cross = t.currency.toUpperCase() !== base;
                const sb = signedBase(t);
                return (
                  <tr key={t.id} className="border-b border-border/60 last:border-0">
                    <td className="tnum whitespace-nowrap py-2.5 pr-3 text-secondary-text">
                      {new Date(t.date + "T12:00:00").toLocaleDateString(locale, {
                        day: "2-digit",
                        month: "short",
                      })}
                    </td>
                    <td className="py-2.5 pr-3">
                      <span className="flex items-center gap-1.5">
                        <span
                          className="h-2 w-2 shrink-0 rounded-full"
                          style={{ backgroundColor: cat?.color ?? "#64748b" }}
                          title={cat?.name}
                        />
                        <span className="text-base leading-none">{cat?.icon ?? "🏷️"}</span>
                        <span className="text-secondary-text">{cat?.name ?? "—"}</span>
                        {t.autoGenerated && (
                          <Link href="/trading/payouts" title={`Payout ${t.sourcePayoutId ?? ""}`}>
                            <Badge tone="info" className="cursor-help">
                              auto
                            </Badge>
                          </Link>
                        )}
                      </span>
                    </td>
                    <td className="max-w-[180px] truncate py-2.5 pr-3 text-secondary-text" title={t.note}>
                      {t.note || <span className="text-muted-foreground">—</span>}
                    </td>
                    <td className="py-2.5 pr-3 text-right">
                      <div
                        className={cn(
                          "tnum font-medium",
                          t.type === "income" ? "text-success" : "text-danger"
                        )}
                      >
                        {masked
                          ? maskMoney()
                          : formatSignedMoney(sb, base, locale)}
                      </div>
                      {cross && !masked && (
                        <div className="tnum text-[11px] text-muted-foreground">
                          {formatMoney(t.amount, t.currency, locale)}{" "}
                          <span className="opacity-70">· {t.currency}</span>
                        </div>
                      )}
                    </td>
                    <td className="py-2.5 pr-3 text-right">
                      <button
                        onClick={() => toggleRecurring(t)}
                        title={t.recurring ? "Ricorrente: disattiva" : "Ricorrente: attiva"}
                        className={cn(
                          "rounded p-1 transition-colors",
                          t.recurring
                            ? "text-accent hover:bg-accent/12"
                            : "text-muted-foreground opacity-60 hover:bg-elevated hover:text-foreground hover:opacity-100"
                        )}
                        aria-label="Toggle ricorrente"
                      >
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <path d="M21 12a9 9 0 1 1-2.64-6.36M21 3v6h-6" />
                        </svg>
                      </button>
                    </td>
                    <td className="py-2.5 text-right">
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => setToDelete(t)}
                        aria-label="Elimina transazione"
                        className="text-muted-foreground hover:text-danger"
                      >
                        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                          <path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 11v6M14 11v6" />
                        </svg>
                      </Button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      <ConfirmDialog
        open={toDelete != null}
        onClose={() => setToDelete(null)}
        onConfirm={confirmDelete}
        title="Eliminare la transazione?"
        message={
          toDelete?.autoGenerated
            ? "Viene eliminata solo la transazione: il payout collegato in Trading resta invariato."
            : "Questa azione non può essere annullata."
        }
        confirmLabel="Elimina"
      />
    </Card>
  );
}
