"use client";
// ============================================================
// ASCEND — Backup / Export (spec 7) · v2 rich
// - Backup completo JSON (download anchor, no librerie)
// - Export CSV per sezione (separatore ;, virgola decimale)
// - Restore da file .json con drag & drop + conferma sovrascrittura
// ============================================================

import React, { useRef, useState } from "react";
import { useDB, updateDB } from "@/lib/storage";
import { seedDB, getAccount, getCategory, setupName } from "@/lib/db";
import { todayKey } from "@/lib/dates";
import type { DB, Transaction, Trade, TradingAccount, Book, Workout, PCUsageLog } from "@/lib/types";
import { exportCollectionCsv, exportDbBackup, downloadBlob, csvNumber } from "@/lib/export";
import { cn } from "@/lib/cn";
import { SectionHeader } from "@/components/ui/Misc";
import { Card, CardHeader, CardTitle, CardSubtitle } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { ConfirmDialog } from "@/components/ui/Modal";
import { Reveal } from "@/components/ui/Reveal";
import { Icon, type IconName } from "@/components/ui/Icon";

const LAST_BACKUP_KEY = "ascend:lastbackup";

function readLastBackup(): string | null {
  try {
    return window.localStorage.getItem(LAST_BACKUP_KEY);
  } catch {
    return null;
  }
}

function writeLastBackup(iso: string): void {
  try {
    window.localStorage.setItem(LAST_BACKUP_KEY, iso);
  } catch {
    // ignorato
  }
}

function formatLastBackup(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleString("it-IT", {
    day: "numeric",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/** Valida che l'oggetto abbia i campi minimi di un backup Ascend. */
function validateBackup(v: unknown): { ok: boolean; missing?: string } {
  if (typeof v !== "object" || v === null || Array.isArray(v)) {
    return { ok: false, missing: "il file non è un oggetto di dati" };
  }
  const o = v as Record<string, unknown>;
  if (typeof o.version !== "number") {
    return { ok: false, missing: "version" };
  }
  const missing: string[] = [];
  const arrKeys = [
    "categories",
    "transactions",
    "accounts",
    "trades",
    "setups",
    "books",
    "workouts",
    "pcUsageLogs",
  ];
  for (const k of arrKeys) {
    if (!Array.isArray(o[k])) missing.push(k);
  }
  if (typeof o.settings !== "object" || o.settings === null) missing.push("settings");
  if (missing.length) return { ok: false, missing: missing.join(", ") };
  return { ok: true };
}

type Msg = { type: "ok" | "error"; text: string } | null;

export default function ExportPage() {
  const db = useDB();
  const [lastBackup, setLastBackup] = useState<string | null>(() =>
    typeof window === "undefined" ? null : readLastBackup()
  );
  const [msg, setMsg] = useState<Msg>(null);
  const [selectedName, setSelectedName] = useState<string | null>(null);
  const [pending, setPending] = useState<DB | null>(null);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const stamp = todayKey(db.settings.timezone);

  // --- Backup completo ------------------------------------------------
  const handleBackup = () => {
    downloadBlob(exportDbBackup(), `ascend-backup-${stamp}.json`);
    const iso = new Date().toISOString();
    writeLastBackup(iso);
    setLastBackup(iso);
    setMsg({ type: "ok", text: "Backup JSON scaricato. Conservalo in un posto sicuro." });
  };

  // --- Export CSV ------------------------------------------------------
  const downloadCsv = (baseName: string, blob: Blob) => downloadBlob(blob, `${baseName}-${stamp}.csv`);

  // Transazioni: data · tipo · categoria · importo · valuta · tasso · nota · auto_generated · source
  const txMapping: Record<string, (t: Transaction) => string> = {
    Data: (t) => t.date,
    Tipo: (t) => (t.type === "income" ? "Entrata" : "Uscita"),
    Categoria: (t) => getCategory(db, t.categoryId)?.name ?? "—",
    Importo: (t) => csvNumber(t.amount),
    Valuta: (t) => t.currency,
    Tasso: (t) => csvNumber(t.exchangeRate),
    Nota: (t) => t.note ?? "",
    "Auto generato": (t) => (t.autoGenerated ? "sì" : "no"),
    Sorgente: (t) => t.sourcePayoutId ?? "",
  };

  // Trade: data chiusura · account · strumento · direzione · entry · exit · size · stop · target ·
  //        resultNative · resultR · setup · emozione · descrizione
  const tradeMapping: Record<string, (t: Trade) => string> = {
    "Data chiusura": (t) => t.closeDate,
    Account: (t) => getAccount(db, t.accountId)?.name ?? "—",
    Strumento: (t) => t.instrument,
    Direzione: (t) => (t.direction === "long" ? "Long" : "Short"),
    Entry: (t) => csvNumber(t.entry),
    Exit: (t) => csvNumber(t.exit),
    Size: (t) => csvNumber(t.size),
    Stop: (t) => csvNumber(t.stop),
    Target: (t) => csvNumber(t.target),
    "Risultato (valuta)": (t) => csvNumber(t.resultNative),
    "Risultato (R)": (t) => csvNumber(t.resultR),
    Setup: (t) => setupName(db, t.setupId),
    Emozione: (t) => t.emotion ?? "",
    Descrizione: (t) => t.description ?? "",
  };

  const accountMapping: Record<string, (a: TradingAccount) => string> = {
    Nome: (a) => a.name,
    Tipo: (a) => (a.type === "prop" ? "Prop" : "Personale"),
    "Valuta nativa": (a) => a.nativeCurrency,
    Capitale: (a) => csvNumber(a.capital),
    Stato: (a) =>
      a.status === "eval" ? "Valutazione" : a.status === "superato" ? "Superato" : a.status === "finanziato" ? "Finanziato" : "Bruciato",
    Firma: (a) => a.firm ?? "",
    Timezone: (a) => a.tradingDayTimezone,
    Rollover: (a) => a.tradingDayRolloverTime,
    "Daily loss limit": (a) => csvNumber(a.dailyLossLimit),
    "Max loss limit": (a) => csvNumber(a.maxLossLimit),
    "Base rate": (a) => csvNumber(a.baseRate),
    Archiviato: (a) => (a.archived ? "sì" : "no"),
  };

  const bookMapping: Record<string, (b: Book) => string> = {
    Titolo: (b) => b.title,
    Autore: (b) => b.author,
    Stato: (b) => (b.status === "da_leggere" ? "Da leggere" : b.status === "in_corso" ? "In corso" : "Finito"),
    "Pagine totali": (b) => csvNumber(b.totalPages),
    "Pagine lette": (b) => csvNumber(b.pagesRead),
    Voto: (b) => csvNumber(b.rating),
    Note: (b) => b.notes ?? "",
    Citazioni: (b) => b.quotes ?? "",
    Iniziato: (b) => b.startDate ?? "",
    Finito: (b) => b.endDate ?? "",
    Creato: (b) => b.createdAt,
    Aggiornato: (b) => b.updatedAt,
  };

  const workoutMapping: Record<string, (w: Workout) => string> = {
    Data: (w) => w.date,
    Tipo: (w) => w.type,
    "Durata (min)": (w) => csvNumber(w.durationMin),
    PR: (w) => w.pr ?? "",
    Nota: (w) => w.note ?? "",
  };

  const pcMapping: Record<string, (p: PCUsageLog) => string> = {
    Data: (p) => p.date,
    "Categoria (id)": (p) => p.categoryId,
    Minuti: (p) => csvNumber(p.minutes),
    Sorgente: (p) => (p.source === "manuale" ? "Manuale" : p.source === "csv" ? "CSV" : "ActivityWatch"),
  };

  const csvSections: { key: string; label: string; icon: IconName; count: number; run: () => void }[] = [
    { key: "transazioni", label: "Transazioni", icon: "coins", count: db.transactions.length, run: () => downloadCsv("ascend-transazioni", exportCollectionCsv(db.transactions, txMapping)) },
    { key: "trades", label: "Trade", icon: "activity", count: db.trades.length, run: () => downloadCsv("ascend-trades", exportCollectionCsv(db.trades, tradeMapping)) },
    { key: "accounts", label: "Account trading", icon: "building", count: db.accounts.length, run: () => downloadCsv("ascend-account", exportCollectionCsv(db.accounts, accountMapping)) },
    { key: "libri", label: "Libri", icon: "book-open", count: db.books.length, run: () => downloadCsv("ascend-libri", exportCollectionCsv(db.books, bookMapping)) },
    { key: "allenamenti", label: "Allenamenti", icon: "dumbbell", count: db.workouts.length, run: () => downloadCsv("ascend-allenamenti", exportCollectionCsv(db.workouts, workoutMapping)) },
    { key: "usopc", label: "Log uso PC", icon: "monitor", count: db.pcUsageLogs.length, run: () => downloadCsv("ascend-usopc", exportCollectionCsv(db.pcUsageLogs, pcMapping)) },
  ];

  // --- Restore (file input + drag & drop) ------------------------------
  const handleFileObject = async (file: File) => {
    setSelectedName(file.name);
    setMsg(null);
    setPending(null);
    try {
      const text = await file.text();
      const parsed = JSON.parse(text) as unknown;
      const check = validateBackup(parsed);
      if (!check.ok) {
        setMsg({ type: "error", text: `Formato non valido: manca/malformato ${check.missing}.` });
        return;
      }
      setPending(parsed as DB);
      setConfirmOpen(true);
    } catch {
      setMsg({ type: "error", text: "File non valido: JSON malformato o non leggibile." });
    }
  };

  const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = ""; // consente di ri-selezionare lo stesso file
    if (!file) return;
    void handleFileObject(file);
  };

  const doRestore = () => {
    if (!pending) return;
    updateDB(() => ({
      ...seedDB(),
      ...pending,
      settings: { ...seedDB().settings, ...pending.settings },
    }));
    setMsg({
      type: "ok",
      text: `Backup ripristinato: ${pending.transactions.length} transazioni, ${pending.trades.length} trade, ${pending.accounts.length} account, ${pending.books.length} libri, ${pending.workouts.length} allenamenti.`,
    });
    setPending(null);
    setConfirmOpen(false);
    setSelectedName(null);
  };

  const totalRows =
    db.transactions.length +
    db.trades.length +
    db.accounts.length +
    db.books.length +
    db.workouts.length +
    db.pcUsageLogs.length;

  return (
    <div className="space-y-6">
      <SectionHeader
        kicker="Backup"
        title="Backup / Export"
        subtitle="I tuoi dati vivono su questo dispositivo: scarica una copia o ripristinala in qualsiasi momento."
      />

      {msg && (
        <div
          className={cn(
            "flex items-center gap-2.5 rounded-xl border px-4 py-3 text-sm font-medium animate-pop",
            msg.type === "ok"
              ? "border-success/30 bg-success/10 text-success"
              : "border-danger/30 bg-danger/10 text-danger"
          )}
        >
          {msg.type === "ok" ? (
            <Icon name="check" size={16} />
          ) : (
            <Icon name="alert" size={16} />
          )}
          {msg.text}
        </div>
      )}

      {/* ---- Backup completo ---- */}
      <Reveal>
        <Card hairline="accent" scan>
          <CardHeader>
            <div>
              <CardTitle>Backup completo</CardTitle>
              <CardSubtitle>
                Un file JSON con l&apos;intero database ({totalRows} righe totali). Perfetto per archiviare o migrare i dati.
              </CardSubtitle>
            </div>
            <Badge tone="info">JSON</Badge>
          </CardHeader>
          <div className="flex flex-wrap items-center gap-3">
            <Button size="lg" glow onClick={handleBackup}>
              <Icon name="download" size={16} strokeWidth={2.2} />
              Scarica backup JSON
            </Button>
            {lastBackup ? (
              <Badge tone="success" pulse>
                ● Ultimo backup · {formatLastBackup(lastBackup)}
              </Badge>
            ) : (
              <Badge>mai fatto</Badge>
            )}
          </div>
        </Card>
      </Reveal>

      {/* ---- Export CSV per sezione ---- */}
      <Reveal delay={80}>
        <Card>
          <CardHeader>
            <div>
              <CardTitle>Export CSV per sezione</CardTitle>
              <CardSubtitle>
                File .csv (separatore ; , virgola decimale) apribili in Excel, Sheets e Numbers.
              </CardSubtitle>
            </div>
            <Badge>CSV</Badge>
          </CardHeader>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
            {csvSections.map((s) => (
              <Button
                key={s.key}
                variant="subtle"
                className="justify-between rounded-xl border border-border-strong/60 hover:border-accent/40 hover:shadow-[0_0_22px_-6px_var(--accent-glow)]"
                onClick={s.run}
              >
                <span className="flex items-center gap-2">
                  <span className="flex h-6 w-6 items-center justify-center rounded-md bg-elevated">
                    <Icon name={s.icon} size={14} className="text-foreground" />
                  </span>
                  {s.label}
                </span>
                <span className="flex items-center gap-1.5">
                  <span className="rounded-full bg-elevated px-2 py-0.5 text-[11px] tnum text-muted-foreground">
                    {s.count}
                  </span>
                  <Icon name="download" size={14} className="text-accent" />
                </span>
              </Button>
            ))}
          </div>
          <p className="mt-3 text-xs leading-relaxed text-muted-foreground">
            Sezioni vuote generano comunque il file con la sola intestazione.
          </p>
        </Card>
      </Reveal>

      {/* ---- Restore backup ---- */}
      <Reveal delay={140}>
        <Card hairline="danger">
          <CardHeader>
            <div>
              <CardTitle>Restore backup</CardTitle>
              <CardSubtitle>
                Ripristina un file .json esportato da Ascend. L&apos;operazione sovrascrive tutti i dati attuali.
              </CardSubtitle>
            </div>
            <Badge tone="danger">sovrascrive</Badge>
          </CardHeader>

          <div
            role="button"
            tabIndex={0}
            aria-label="Scegli o trascina un file di backup JSON"
            onClick={() => fileInputRef.current?.click()}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                fileInputRef.current?.click();
              }
            }}
            onDragOver={(e) => {
              e.preventDefault();
              setDragOver(true);
            }}
            onDragLeave={() => setDragOver(false)}
            onDrop={(e) => {
              e.preventDefault();
              setDragOver(false);
              const file = e.dataTransfer.files?.[0];
              if (file) void handleFileObject(file);
            }}
            className={cn(
              "flex cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed px-4 py-8 text-center transition-[border-color,background-color,box-shadow] duration-300",
              dragOver
                ? "border-accent bg-accent-dim shadow-[0_0_30px_-8px_var(--accent-glow)]"
                : "border-border-strong bg-muted/30 hover:border-accent/40 hover:bg-accent-dim/40"
            )}
          >
            <span
              className={cn(
                "flex h-11 w-11 items-center justify-center rounded-xl transition-[transform,background-color] duration-300",
                dragOver ? "scale-110 bg-accent/20" : "bg-elevated"
              )}
            >
              <Icon name="upload" size={22} className="text-foreground" />
            </span>
            <p className="text-sm font-medium leading-relaxed text-secondary-text">
              {dragOver ? "Rilascia il file qui" : "Trascina il file .json qui o clicca per sceglierlo"}
            </p>
            <p className="text-xs text-muted-foreground">
              Solo backup esportati da Ascend (formato JSON).
            </p>
            <input
              ref={fileInputRef}
              type="file"
              accept=".json,application/json"
              className="hidden"
              onChange={handleFile}
            />
          </div>

          {selectedName && (
            <div className="mt-3 flex items-center gap-2 animate-pop">
              <Badge tone="info" pulse>
                <Icon name="clipboard" size={11} /> {selectedName}
              </Badge>
              <span className="text-xs text-muted-foreground">
                in attesa di conferma…
              </span>
            </div>
          )}

          {db.transactions.length + db.trades.length > 0 && (
            <p className="mt-3 flex items-center gap-1.5 text-xs text-danger/90">
              <Icon name="alert" size={12} className="shrink-0" />
              Attenzione: hai dati già salvati. Il restore li sostituirà completamente.
            </p>
          )}
        </Card>
      </Reveal>

      <ConfirmDialog
        open={confirmOpen}
        onClose={() => {
          setConfirmOpen(false);
          setPending(null);
        }}
        onConfirm={doRestore}
        title="Sovrascrivere tutti i dati?"
        message="Il backup selezionato sostituirà tutti i dati attuali di Ascend. Questa azione non può essere annullata."
        confirmLabel="Ripristina"
      />
    </div>
  );
}
