"use client";
// ============================================================
// ASCEND — Payout & Certificati (specifica v3 §4.2 + §4.3)
// - CRUD Spese firm (eval / reset / sub) per account
// - CRUD Payout con tasso FX (prefill quoteFx, editabile)
// - Sync automatico payout → Transaction income nelle Finanze
//   (categoria "Payout trading" trovata per nome o creata)
// - Netto reale per account (base) colorato
// - Muro dei certificati: trofei 🏆 / payout 💰 / patrimonio gestito
// ============================================================

import { useEffect, useState } from "react";
import Link from "next/link";
import { useDB, updateDB, upsert, removeById, uid, nowISO } from "@/lib/storage";
import { SectionHeader, EmptyState } from "@/components/ui/Misc";
import { Card, CardHeader, CardTitle } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Modal, ConfirmDialog } from "@/components/ui/Modal";
import { Field, Input, Select, TextArea } from "@/components/ui/Field";
import { Badge } from "@/components/ui/Badge";
import { StatCard } from "@/components/ui/StatCard";
import { formatMoney, formatSignedMoney } from "@/lib/format";
import { convertToBase, accountBaseRate } from "@/lib/compute";
import { quoteFx, COMMON_CURRENCIES } from "@/lib/fx";
import { todayKey, labelDayKey } from "@/lib/dates";
import { moneyMasked, maskMoney } from "@/lib/privacy";
import type {
  DB,
  Category,
  TradingAccount,
  Payout,
  FirmExpense,
  FirmExpenseType,
  AccountStatus,
  Transaction,
} from "@/lib/types";

// ============================================================
// Metadati / helper locali (niente modifiche a src/lib)
// ============================================================

const STATUS_META: Record<
  AccountStatus,
  { label: string; tone: "default" | "info" | "success" | "danger" | "warning" }
> = {
  eval: { label: "Valutazione", tone: "info" },
  superato: { label: "Superato", tone: "success" },
  finanziato: { label: "Finanziato", tone: "success" },
  bruciato: { label: "Bruciato", tone: "danger" },
};

const EXPENSE_TYPE_LABEL: Record<FirmExpenseType, string> = {
  eval: "Fee valutazione",
  reset: "Reset",
  sub: "Abbonamento",
};

/** Categoria 'Payout trading' trovata per nome; se manca la crea (📈 #22c55e income). */
function ensurePayoutCategory(db: DB): { db: DB; categoryId: string } {
  const existing = db.categories.find(
    (c) => c.name.trim().toLowerCase() === "payout trading"
  );
  if (existing) return { db, categoryId: existing.id };
  const cat: Category = {
    id: uid(),
    name: "Payout trading",
    type: "income",
    icon: "📈",
    color: "#22c55e",
  };
  return { db: { ...db, categories: [...db.categories, cat] }, categoryId: cat.id };
}

/** Create/update della Transaction auto-generata collegata a un payout. */
function syncPayoutTransaction(db: DB, payout: Payout): DB {
  const { db: next, categoryId } = ensurePayoutCategory(db);
  const existing = next.transactions.find((t) => t.sourcePayoutId === payout.id);
  const txn: Transaction = {
    id: existing?.id ?? uid(),
    amount: payout.amount,
    currency: payout.currency,
    exchangeRate: payout.exchangeRate,
    type: "income",
    categoryId,
    date: payout.date,
    note: payout.note ? `Payout: ${payout.note}` : "Payout trading",
    autoGenerated: true,
    sourcePayoutId: payout.id,
    createdAt: existing?.createdAt ?? nowISO(),
  };
  return { ...next, transactions: upsert(next.transactions, txn) };
}

function roundRate(r: number): number {
  return Math.round(r * 1e6) / 1e6;
}

// ============================================================
// Modal condivisa — nuovo/aggiungi payout o spesa firm
// ============================================================

type FormMode = "payout" | "expense";

function ItemModal({
  open,
  onClose,
  mode,
  defaultAccountId,
  editItem,
  accounts,
  baseCurrency,
  timezone,
  locale,
}: {
  open: boolean;
  onClose: () => void;
  mode: FormMode;
  defaultAccountId: string;
  editItem: Payout | FirmExpense | null;
  accounts: TradingAccount[];
  baseCurrency: string;
  timezone: string;
  locale: string;
}) {
  const editing = editItem != null;
  const [account, setAccount] = useState("");
  const [type, setType] = useState<FirmExpenseType>("eval");
  const [amount, setAmount] = useState("");
  const [currency, setCurrency] = useState("");
  const [rate, setRate] = useState("1");
  const [rateAuto, setRateAuto] = useState(false);
  const [date, setDate] = useState("");
  const [note, setNote] = useState("");

  const selAccount = accounts.find((a) => a.id === account);
  const sameBase = currency.toUpperCase() === baseCurrency.toUpperCase();
  const amountNum = parseFloat(amount);
  const rateNum = parseFloat(rate);
  const amountValid = isFinite(amountNum) && amountNum > 0;
  const rateValid = isFinite(rateNum) && rateNum > 0;
  const canSave = !!selAccount && amountValid && rateValid && date !== "" && account !== "";

  // Reset / init del form all'apertura
  useEffect(() => {
    if (!open) return;
    if (editing && editItem) {
      setAccount(editItem.accountId);
      if (mode === "expense") setType((editItem as FirmExpense).type);
      setAmount(String(editItem.amount));
      setCurrency(editItem.currency);
      setRate(String(editItem.exchangeRate ?? 1));
      setRateAuto(false); // non sovrascrivere il tasso già salvato
      setDate(editItem.date);
      setNote(editItem.note ?? "");
    } else {
      const first = accounts.find((a) => a.id === defaultAccountId) ?? accounts[0];
      setAccount(first?.id ?? "");
      setType("eval");
      setAmount("");
      setCurrency(first?.nativeCurrency ?? baseCurrency);
      setRate("1");
      setRateAuto(true); // valuta nativa → quota il tasso se ≠ base (effect sotto)
      setDate(todayKey(timezone));
      setNote("");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, editItem, mode, defaultAccountId]);

  // Prefill FX: quando valuta ≠ base e tasso non toccato a mano
  useEffect(() => {
    if (!open || !rateAuto) return;
    if (sameBase) {
      setRate("1");
      return;
    }
    let alive = true;
    quoteFx(currency, baseCurrency).then((q) => {
      if (alive && q) setRate(String(roundRate(q.rate)));
    });
    return () => {
      alive = false;
    };
  }, [open, currency, baseCurrency, rateAuto, sameBase]);

  const onCurrencyChange = (next: string) => {
    setCurrency(next);
    setRateAuto(true); // nuova valuta → riquota
  };

  const save = () => {
    if (!canSave) return;
    const finalRate = rateValid ? rateNum : 1;
    if (mode === "expense") {
      const item: FirmExpense = {
        id: editing ? (editItem as FirmExpense).id : uid(),
        accountId: account,
        type,
        amount: amountNum,
        currency,
        exchangeRate: finalRate,
        date,
        note: note.trim() || undefined,
        createdAt: editing ? (editItem as FirmExpense).createdAt : nowISO(),
      };
      updateDB((d) => ({ ...d, firmExpenses: upsert(d.firmExpenses, item) }));
    } else {
      const item: Payout = {
        id: editing ? (editItem as Payout).id : uid(),
        accountId: account,
        amount: amountNum,
        currency,
        exchangeRate: finalRate,
        date,
        note: note.trim() || undefined,
        createdAt: editing ? (editItem as Payout).createdAt : nowISO(),
      };
      // sync auto con la Transaction income nelle Finanze
      updateDB((d) => syncPayoutTransaction(d, item));
    }
    onClose();
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title={editing ? (mode === "payout" ? "Modifica payout" : "Modifica spesa firm") : mode === "payout" ? "Nuovo payout" : "Nuova spesa firm"}
      footer={
        <>
          <Button variant="ghost" onClick={onClose}>Annulla</Button>
          <Button onClick={save} disabled={!canSave}>{editing ? "Salva" : "Aggiungi"}</Button>
        </>
      }
    >
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <Field label="Account" className={mode === "expense" ? "" : "sm:col-span-2"}>
          <Select value={account} onChange={(e) => { const v = e.target.value; setAccount(v); const a = accounts.find((x) => x.id === v); if (a && !editing) { setCurrency(a.nativeCurrency); setRateAuto(true); } }}>
            <option value="" disabled>Seleziona account</option>
            {accounts.map((a) => (
              <option key={a.id} value={a.id}>{a.name}{a.archived ? " (archiviato)" : ""}</option>
            ))}
          </Select>
        </Field>

        {mode === "expense" && (
          <Field label="Tipo">
            <Select value={type} onChange={(e) => setType(e.target.value as FirmExpenseType)}>
              {(Object.keys(EXPENSE_TYPE_LABEL) as FirmExpenseType[]).map((t) => (
                <option key={t} value={t}>{EXPENSE_TYPE_LABEL[t]}</option>
              ))}
            </Select>
          </Field>
        )}

        <Field label={mode === "payout" ? "Importo ricevuto" : "Importo"}>
          <Input
            type="number"
            inputMode="decimal"
            step="0.01"
            min="0"
            placeholder="0.00"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
          />
        </Field>

        <Field label="Valuta">
          <Select value={currency} onChange={(e) => onCurrencyChange(e.target.value)}>
            {COMMON_CURRENCIES.map((c) => (
              <option key={c} value={c}>{c}</option>
            ))}
          </Select>
        </Field>

        <Field label={`Tasso (${baseCurrency} per 1 ${currency || "…"})`}>
          <Input
            type="number"
            inputMode="decimal"
            step="any"
            min="0"
            value={rate}
            disabled={sameBase}
            onChange={(e) => { setRate(e.target.value); setRateAuto(false); }}
          />
          {!sameBase && (
            <p className="mt-1 text-[11px] text-muted-foreground">
              1 {currency || "…"} = {rate && rateValid ? rate : "…"} {baseCurrency}
              {rateAuto ? " · quotato automaticamente" : " · manuale"}
            </p>
          )}
        </Field>

        <Field label="Data">
          <Input type="date" value={date} onChange={(e) => setDate(e.target.value)} />
        </Field>

        <Field label="Nota (facoltativa)" className="sm:col-span-2">
          <TextArea
            placeholder={mode === "payout" ? "Firm, periodo, note…" : "Motivo della spesa…"}
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
        </Field>
      </div>
    </Modal>
  );
}

// ============================================================
// Pagina
// ============================================================

export default function PayoutsPage() {
  const db = useDB();
  const base = db.settings.baseCurrency;
  const locale = db.settings.locale;
  const hidden = moneyMasked(db.settings.privacyMode);

  const accounts = db.accounts;
  const activeAccounts = accounts.filter((a) => !a.archived);
  const payouts = db.payouts;
  const expenses = db.firmExpenses;

  const [modal, setModal] = useState<{
    mode: FormMode;
    defaultAccountId: string;
    editItem: Payout | FirmExpense | null;
  } | null>(null);
  const [confirm, setConfirm] = useState<{ kind: FormMode; id: string } | null>(null);

  // Formatter money (privacy-aware)
  const M = (amount: number, currency: string, signed = false) =>
    hidden
      ? maskMoney()
      : signed
        ? formatSignedMoney(amount, currency, locale)
        : formatMoney(amount, currency, locale);

  // ---- KPI globali (valuta base) ----
  const sumBase = (list: { amount: number; exchangeRate: number }[]) =>
    list.reduce((s, x) => s + convertToBase(x.amount, x.exchangeRate), 0);
  const totalPayoutBase = sumBase(payouts);
  const totalExpenseBase = sumBase(expenses);
  const netTotal = totalPayoutBase - totalExpenseBase;
  const patrimonio = activeAccounts.reduce(
    (s, a) => s + convertToBase(a.capital, accountBaseRate(a, base)),
    0
  );

  // Netto reale per account
  const netOf = (accId: string) => {
    const pay = sumBase(payouts.filter((p) => p.accountId === accId));
    const exp = sumBase(expenses.filter((e) => e.accountId === accId));
    return pay - exp;
  };
  const payoutSumOf = (accId: string) => sumBase(payouts.filter((p) => p.accountId === accId));
  const expenseSumOf = (accId: string) => sumBase(expenses.filter((e) => e.accountId === accId));

  const accountName = (id: string) => accounts.find((a) => a.id === id)?.name ?? "Account eliminato";

  // ---- Muro dei certificati ----
  const earned = activeAccounts
    .filter((a) => a.status === "superato" || a.status === "finanziato")
    .sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  const payoutsSorted = [...payouts].sort((a, b) => b.date.localeCompare(a.date));

  const fmtISO = (iso: string) =>
    new Date(iso).toLocaleDateString(locale, { day: "numeric", month: "short", year: "numeric" });

  const openNew = (mode: FormMode, accId?: string) =>
    setModal({
      mode,
      defaultAccountId: accId ?? activeAccounts[0]?.id ?? "",
      editItem: null,
    });
  const openEdit = (mode: FormMode, item: Payout | FirmExpense) =>
    setModal({ mode, defaultAccountId: item.accountId, editItem: item });

  const doDelete = () => {
    if (!confirm) return;
    const id = confirm.id;
    if (confirm.kind === "payout") {
      updateDB((d) => ({
        ...d,
        payouts: removeById(d.payouts, id),
        transactions: d.transactions.filter((t) => t.sourcePayoutId !== id),
      }));
    } else {
      updateDB((d) => ({ ...d, firmExpenses: removeById(d.firmExpenses, id) }));
    }
    setConfirm(null);
  };

  // ---- Empty state: nessun account ----
  if (!activeAccounts.length) {
    return (
      <div className="space-y-6">
        <SectionHeader
          title="Payout & Certificati"
          subtitle="Spese firm, payout ricevuti e muro dei certificati."
        />
        <EmptyState
          icon="🏦"
          title="Nessun account di trading"
          description="Crea un account nella sezione Account per registrare payout e spese firm."
          action={
            <Link href="/trading/accounts">
              <Button variant="outline" size="sm">Vai ad Account</Button>
            </Link>
          }
        />
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <SectionHeader
        title="Payout & Certificati"
        subtitle="Spese firm, payout ricevuti e muro dei certificati."
        action={
          <>
            <Button variant="outline" size="sm" onClick={() => openNew("expense")}>＋ Spesa firm</Button>
            <Button size="sm" onClick={() => openNew("payout")}>＋ Payout</Button>
          </>
        }
      />

      {/* KPI */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          label="Netto reale totale"
          value={
            <span className={netTotal >= 0 ? "text-success" : "text-danger"}>
              {M(netTotal, base, true)}
            </span>
          }
          icon={<span className="text-base">⚖️</span>}
        />
        <StatCard
          label="Payout ricevuti"
          value={M(totalPayoutBase, base)}
          delta={`${payouts.length} payout`}
          icon={<span className="text-base">💰</span>}
        />
        <StatCard
          label="Spese firm"
          value={M(totalExpenseBase, base)}
          delta={`${expenses.length} spese`}
          icon={<span className="text-base">🧾</span>}
        />
        <StatCard
          label="Patrimonio gestito"
          value={M(patrimonio, base)}
          delta={`${activeAccounts.length} account attivi`}
          icon={<span className="text-base">📊</span>}
        />
      </div>

      {/* Muro dei certificati */}
      <section>
        <div className="mb-4">
          <h2 className="text-lg font-semibold tracking-tight">Muro dei certificati</h2>
          <p className="mt-0.5 text-sm text-muted-foreground">
            Eval superate, payout incassati e capitale sotto gestione.
          </p>
        </div>

        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">
          {earned.map((a) => (
            <Card key={a.id} className="flex flex-col items-center justify-center gap-1 text-center">
              <span className="text-3xl">🏆</span>
              <p className="w-full truncate px-1 text-sm font-semibold">{a.name}</p>
              <Badge tone={STATUS_META[a.status].tone}>{STATUS_META[a.status].label}</Badge>
              <p className="text-[11px] text-muted-foreground">dal {fmtISO(a.createdAt)}</p>
            </Card>
          ))}

          {payoutsSorted.map((p) => (
            <Card key={p.id} className="flex flex-col items-center justify-center gap-1 text-center">
              <span className="text-3xl">💰</span>
              <p className="text-lg font-semibold tnum text-success">{M(p.amount, p.currency)}</p>
              <p className="text-[11px] text-muted-foreground">{labelDayKey(p.date, locale)}</p>
              <Badge tone="default">{accountName(p.accountId)}</Badge>
            </Card>
          ))}

          {earned.length === 0 && payouts.length === 0 && (
            <Card className="flex flex-col items-center justify-center gap-1 border-dashed text-center">
              <span className="text-3xl opacity-60">🕳</span>
              <p className="text-xs text-muted-foreground">Ancora nessun trofeo</p>
            </Card>
          )}

          <Card className="flex flex-col items-center justify-center gap-1 border-accent/40 text-center">
            <span className="text-3xl">📊</span>
            <p className="text-lg font-semibold tnum">{M(patrimonio, base)}</p>
            <p className="text-[11px] text-muted-foreground">patrimonio gestito</p>
          </Card>
        </div>
      </section>

      {/* Dettaglio per account */}
      <section>
        <div className="mb-4">
          <h2 className="text-lg font-semibold tracking-tight">Dettaglio per account</h2>
          <p className="mt-0.5 text-sm text-muted-foreground">
            Payout e spese firm, con netto reale convertito in {base}.
          </p>
        </div>

        <div className="space-y-4">
          {activeAccounts.map((acc) => {
            const net = netOf(acc.id);
            const accPayouts = payouts
              .filter((p) => p.accountId === acc.id)
              .sort((a, b) => b.date.localeCompare(a.date));
            const accExpenses = expenses
              .filter((e) => e.accountId === acc.id)
              .sort((a, b) => b.date.localeCompare(a.date));
            return (
              <Card key={acc.id}>
                <CardHeader>
                  <div className="min-w-0">
                    <CardTitle>{acc.name}</CardTitle>
                    <div className="mt-1.5 flex flex-wrap items-center gap-2">
                      <Badge tone={STATUS_META[acc.status].tone}>{STATUS_META[acc.status].label}</Badge>
                      {acc.firm && <span className="text-xs text-muted-foreground">{acc.firm}</span>}
                      <span className="text-xs text-muted-foreground">· {acc.nativeCurrency}</span>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
                      Netto reale
                    </p>
                    <p className={`tnum text-xl font-semibold ${net >= 0 ? "text-success" : "text-danger"}`}>
                      {M(net, base, true)}
                    </p>
                  </div>
                </CardHeader>

                <div className="grid gap-4 md:grid-cols-2">
                  {/* Payout */}
                  <div>
                    <div className="mb-2 flex items-center justify-between">
                      <p className="text-xs font-medium text-secondary-text">
                        Payout
                        {accPayouts.length > 0 && (
                          <span className="ml-1 text-muted-foreground">· tot {M(payoutSumOf(acc.id), base)}</span>
                        )}
                      </p>
                      <Button size="sm" variant="subtle" onClick={() => openNew("payout", acc.id)} aria-label="Nuovo payout">＋</Button>
                    </div>
                    {accPayouts.length === 0 ? (
                      <p className="rounded-lg border border-dashed border-border-strong px-3 py-3 text-center text-xs text-muted-foreground">
                        Nessun payout
                      </p>
                    ) : (
                      <div className="space-y-1.5">
                        {accPayouts.map((p) => (
                          <div key={p.id} className="flex items-center justify-between gap-2 rounded-lg border border-border bg-muted px-3 py-2">
                            <div className="min-w-0">
                              <p className="text-sm font-medium tnum text-success">{M(p.amount, p.currency)}</p>
                              <p className="truncate text-[11px] text-muted-foreground">
                                {labelDayKey(p.date, locale)}
                                {p.currency !== base && ` · ≈ ${M(convertToBase(p.amount, p.exchangeRate), base)}`}
                                {p.note ? ` · ${p.note}` : ""}
                              </p>
                            </div>
                            <div className="flex shrink-0 gap-0.5">
                              <Button size="icon" variant="ghost" onClick={() => openEdit("payout", p)} aria-label="Modifica payout">✏️</Button>
                              <Button size="icon" variant="ghost" onClick={() => setConfirm({ kind: "payout", id: p.id })} aria-label="Elimina payout">🗑</Button>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Spese firm */}
                  <div>
                    <div className="mb-2 flex items-center justify-between">
                      <p className="text-xs font-medium text-secondary-text">
                        Spese firm
                        {accExpenses.length > 0 && (
                          <span className="ml-1 text-muted-foreground">· tot {M(expenseSumOf(acc.id), base)}</span>
                        )}
                      </p>
                      <Button size="sm" variant="subtle" onClick={() => openNew("expense", acc.id)} aria-label="Nuova spesa firm">＋</Button>
                    </div>
                    {accExpenses.length === 0 ? (
                      <p className="rounded-lg border border-dashed border-border-strong px-3 py-3 text-center text-xs text-muted-foreground">
                        Nessuna spesa
                      </p>
                    ) : (
                      <div className="space-y-1.5">
                        {accExpenses.map((e) => (
                          <div key={e.id} className="flex items-center justify-between gap-2 rounded-lg border border-border bg-muted px-3 py-2">
                            <div className="min-w-0">
                              <p className="text-sm font-medium tnum text-danger">{M(e.amount, e.currency)}</p>
                              <p className="truncate text-[11px] text-muted-foreground">
                                {labelDayKey(e.date, locale)}
                                <span className="ml-1 rounded bg-elevated px-1 py-px text-[10px]">{EXPENSE_TYPE_LABEL[e.type]}</span>
                                {e.currency !== base && ` · ≈ ${M(convertToBase(e.amount, e.exchangeRate), base)}`}
                                {e.note ? ` · ${e.note}` : ""}
                              </p>
                            </div>
                            <div className="flex shrink-0 gap-0.5">
                              <Button size="icon" variant="ghost" onClick={() => openEdit("expense", e)} aria-label="Modifica spesa">✏️</Button>
                              <Button size="icon" variant="ghost" onClick={() => setConfirm({ kind: "expense", id: e.id })} aria-label="Elimina spesa">🗑</Button>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </Card>
            );
          })}
        </div>
      </section>

      {/* Modale create/edit */}
      <ItemModal
        open={modal != null}
        onClose={() => setModal(null)}
        mode={modal?.mode ?? "payout"}
        defaultAccountId={modal?.defaultAccountId ?? ""}
        editItem={modal?.editItem ?? null}
        accounts={accounts}
        baseCurrency={base}
        timezone={db.settings.timezone}
        locale={locale}
      />

      {/* Conferma eliminazione */}
      <ConfirmDialog
        open={confirm != null}
        onClose={() => setConfirm(null)}
        onConfirm={doDelete}
        title={confirm?.kind === "payout" ? "Eliminare payout?" : "Eliminare spesa?"}
        message={
          confirm?.kind === "payout"
            ? "Il payout e la transazione collegata nelle Finanze verranno rimossi."
            : "Questa azione non può essere annullata."
        }
        confirmLabel="Elimina"
      />
    </div>
  );
}
